A11.2021.13937
Hafizh Hugo Harman

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
df = pd.read_csv("resto_preprocessedz.csv", delimiter=";")

In [3]:
features = ["District", "subdistrict", "Highest Price", "Lowest Price", "Average Price",
            "Category_Aneka nasi", "Category_Ayam & bebek", "Category_Bakmie",
            "Category_Bakso & soto", "Category_Barat", "Category_Cepat saji",
            "Category_Chinese", "Category_India", "Category_Jajanan", "Category_Jepang",
            "Category_Kopi", "Category_Korea", "Category_Martabak", "Category_Minuman",
            "Category_Pizza & pasta", "Category_Roti", "Category_Sate", "Category_Seafood",
            "Category_Sweets", "Category_Thailand", "Category_Timur Tengah"]
target = "Popularity"

In [4]:
X = df[features]
y = df[target]

In [5]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [7]:
y_pred = knn.predict(X_test)


In [8]:
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

Accuracy: 0.8151979311716729


In [9]:
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:\n', conf_matrix)

Confusion Matrix:
 [[1448   42   51  111]
 [ 105  571   30   57]
 [  84   63  432   51]
 [ 225   48   62 1647]]


In [10]:
class_report = classification_report(y_test, y_pred)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.88      0.82      1652
           1       0.79      0.75      0.77       763
           2       0.75      0.69      0.72       630
           3       0.88      0.83      0.86      1982

    accuracy                           0.82      5027
   macro avg       0.80      0.79      0.79      5027
weighted avg       0.82      0.82      0.81      5027

